name = "StridedViews"
uuid = "4db3bf67-4bd7-4b4e-b153-31dc3fb37143"
authors = ["Lukas Devos <lukas.devos@ugent.be>", "Jutho Haegeman <jutho.haegeman@ugent.be>"]
version = "0.5.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDACore = "bd0ed864-bdfe-4181-a5ed-ce625a5fdea2"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
PtrArrays = "43287f4e-b6f4-7ad1-bb20-aadabca52c3d"

[extensions]
StridedViewsAMDGPUExt = "AMDGPU"
StridedViewsCUDACoreExt = "CUDACore"
StridedViewsFiniteDifferencesExt = "FiniteDifferences"
StridedViewsJLArraysExt = "JLArrays"
StridedViewsPtrArraysExt = "PtrArrays"
StridedViewsAdaptExt = "Adapt"

[compat]
AMDGPU = "2"
Adapt = "4"
CUDACore = "6"
FiniteDifferences = "0.12"
JLArrays = "0.3.1"
LinearAlgebra = "1"
Metal = "1"
PrecompileTools = "1.1"
PtrArrays = "1.2.0"
julia = "1.10"

[workspace]
projects = ["test"]
