name: "Invalidations Check"

on:
  workflow_call:
    inputs:
      run-on-non-default-branches:
        description: "Run on branches that are not the default branch as well"
        default: false
        required: false
        type: boolean
      directory:
        description: "The directory on which JuliaFormatter needs to be run"
        default: "."
        required: false
        type: string
      julia-version:
        description: "Julia version"
        default: "1"
        required: false
        type: string
      concurrent-jobs:
        description: "Run jobs concurrently"
        default: false
        required: false
        type: boolean
      cancel-in-progress:
        description: "Cancel jobs in-progress in favor of a new one in the same concurrency group"
        default: true
        required: false
        type: boolean

concurrency:
  group: "${{ inputs.concurrent-jobs && github.run_id || github.ref  }}:${{ github.workflow }}"
  cancel-in-progress: ${{ !inputs.concurrent-jobs && inputs.cancel-in-progress }}

jobs:
  evaluate-invalidations:
    if: ${{ inputs.run-on-non-default-branches || github.base_ref == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    steps:
    - uses: julia-actions/setup-julia@v2
      with:
        version: '${{ inputs.julia-version }}'

    - name: "Checkout ${{ github.repository }}#${{ github.head_ref || github.ref_name }}"
      uses: actions/checkout@v4
    - uses: julia-actions/julia-buildpkg@v1
    - name: "Count invalidations in PR"
      id: invalidations-in-pr
      uses: julia-actions/julia-invalidations@v1

    - name: "Checkout ${{ github.repository }}#${{ github.event.repository.default_branch }}"
      uses: actions/checkout@v4
      with:
        ref: "${{ github.event.repository.default_branch }}"
    - uses: julia-actions/julia-buildpkg@v1
    - name: "Count baseline invalidations"
      id: invalidations-baseline
      uses: julia-actions/julia-invalidations@v1

    - name: "Report invalidation counts"
      run: |
        echo "Invalidations on ${{ github.event.repository.default_branch }}: ${{ steps.invalidations-baseline.outputs.total }} (${{ steps.invalidations-baseline.outputs.deps }} via deps)" >> $GITHUB_STEP_SUMMARY
        echo "Invalidations on ${{ github.head_ref || github.ref_name }}: ${{ steps.invalidations-in-pr.outputs.total }} (${{ steps.invalidations-in-pr.outputs.deps }} via deps)" >> $GITHUB_STEP_SUMMARY

    - name: "Check if the PR increases the number of invalidations"
      run: |
        if [ ${{ steps.invalidations-in-pr.outputs.total }} -gt ${{ steps.invalidations-baseline.outputs.total }} ]; then
          echo "More invalidations have been introduced."
          exit 1
        fi